services:
  api:
    build: .
    command: sh -c "uvicorn --factory --reload --host 0.0.0.0 --port 8000 task_manager.main:create_app"
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_migration:
    build: .
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./alembic.ini:/app/alembic.ini:ro
      - ./src/task_manager/database/sqlalchemy_db/migrations:/app/src/task_manager/database/sqlalchemy_db/migrations:ro
    command: ["python", "-m", "alembic", "upgrade", "head"]
